### ISSUE TITLE
fugitive zsh:1 command not found: git

### ISSUE THREAD

**Issue by naclander** [seletskiy/vim-refugi#5]
Unfortunately for me, `git clone vim-refugi` did not "just work".

I'm using **pathogen**, and I cloned vim-refugi into my **neovim** `bundle` directory. 

When attempting to run `:Gblame` I get the error `fugitive zsh:1 command not found: git`.

I get the same error when attempting to run `:Gstatus`

**Comment by seletskiy** [comment]
@naclander: `git` should be installed on the remote system as well.

**Comment by naclander** [comment]
Ah, the issue was that git on my remove system was not installed in the standard location ( /usr/bin/git ). Thanks!
